### ISSUE TITLE
Ability to exclude resources during converge

### ISSUE THREAD

**Issue by peterabbott** [neillturner/kitchen-puppet#101]
It would be nice to have an "ignores" file to prevent particular directories/files from being copied to the target container during converge stage. It would be something like the chefignore file in the Chef world.

A use case is, when you don't have gem's installed globally (ie. a CI environment) and use bundler to execute the kitchen commands. By default the gem's get installed into `./vendor/bundle` so they end up adding a lot of time to the testing when the get copied. One option is to remember to install to a path outside the project space, but it would just be easier to be able to certain files not to be copied.  

I scanned the open issues and didn't see anything matching. I might have a go at adding this but wanted to pose the question in case it is being looked at already or it is there and I am just blind :)

**Comment by neillturner** [comment]
The chefignore file is located at the root of the /cookbooks subdirectory in the chef-repo. if we have a puppetignore file should it be at the top level of the puppet repo or inside the directory containing the modules like chef. My guess is it should be top-level. 
it will be the same as the chefignore file as per:
 https://www.chef.io/blog/2011/04/29/chef-0-10-preview-chefignore/
then we can code a simple ruby 
   File.fnmatch

**Comment by peterabbott** [comment]
Thanks for the reply.

The chefignores file actually works for individual chef recipes too, at least that is how I have been using it on individual recipes and how the Chef guys recommend to test a recipe/module.

I am still learning Puppet, so deciding on my workflow. I am using Test Kitchen to test the module before introducing it to a wider ecosystem. I tried Beaker, but it just feels a bit less matured compared to Test Kitchen.

**Comment by neillturner** [comment]
ok i'll support it in the modules like chef cookbooks. I'm a consultant so i work with chef, puppet and ansible so I like using the same tooling (ie test kitchen)  as it makes easier to switch because config management tools on different contracts. Rather than having to swap between test kitchen for chef and beaker for puppet. ansible doesn't really have an equivalent so test-kitchen with ansible it is really the only way to do iterative development and testing. 

 One other thing  I do with puppet is use my roles module at the puppet forge. 
  https://forge.puppetlabs.com/neillturner/role
I use this to implement roles like chef by setting custom facts and support different environments and have different parameters in hiera. (this is like the chef environment definition)

I also follow the library, application pattern and prefix application modules with a company prefix and use librarian-puppet for library modules from puppet forge and lock the version (just like berks for chef). test-kitchen supports all this which is nice. that way 95% of you code can be in library modules and not in your puppet repo so this keeps the puppet repo small. The application modules just call the library modules so that keeps them simple.

**Comment by peterabbott** [comment]
awesome. Thanks for the info. So far I am still preferring Chef, but I am sure I will hit that aha moment soon :) Like you say, Test Kitchen helps with the iterative development and learning.

**Comment by neillturner** [comment]
ansible is probably best. i find i can work just as well in puppet or chef as long as i follow certain best practices. Some things in chef are better an some things in puppet are better. Chef i find complex (ie 15 ways to do attributes) so the secret is to not use the complex features of chef. 
 you can see how i do puppet using a sample puppet repo: 
    https://github.com/neillturner/puppet_repo
using my roles module.

**Comment by neillturner** [comment]
I have just added a ignore_spec_fixtures parameter that will ignore spec/fixtures. 
Actually kitchen-puppet only copies directories 
 modules manifests files hiera hiera.yaml facter spec 
for the repository so i don't want to implement equivalent of chefignores. 
If you have a specific directory you don't want copies for some reason then we can look at it. 
So closing this as not implemented. If you have a specific directory you wish to ignore create a new issue.
