### ISSUE TITLE
Windows proxy install not working

### ISSUE THREAD

**Issue by hbuckle** [neillturner/kitchen-puppet#153]
Installing puppet on Windows through a proxy does not work - the install code is wrong

It should be something along the lines of 

if ('#{http_proxy}' -ne '')
{
wget $MsiUrl -UseBasicParsing -OutFile "C:/puppet.msi" -Proxy #{http_proxy}
$process = Start-Process -FilePath msiexec.exe -Wait -PassThru -ArgumentList '/qn', '/norestart', '/i', 'C:\\puppet.msi'
}
else
{
$process = Start-Process -FilePath msiexec.exe -Wait -PassThru -ArgumentList '/qn', '/norestart', '/i', $MsiUrl
}

Currently it looks like a Ruby if statement embedded in the PowerShell install script.

**Comment by hbuckle** [comment]
In fact the install on Windows does not work at all now, with or without a proxy, as the PowerShell script is invalid

**Comment by neillturner** [comment]
sorry about that. i normally apply PRs that folks write unless there is a serious problem with them.  This time i got a bit smart. -) Actually its easy to get confused if the variables are resolved when ruby runs or the generated script runs. I've updated the code to be your original PR which is what i should of done originally. Hopefully i have got it right this.  fixed in version 1.46.2,
I need to add tests for windows.
