### ISSUE TITLE
Hiera datadir in Windows

### ISSUE THREAD

**Issue by RamblingCookieMonster** [neillturner/kitchen-puppet#155]
Hi all!

I'm somewhat new to both Puppet and Test-Kitchen, apologies if this is by design...

Two questions that boil down to `would it make sense, and would it break anything if we make it a bit easier to work with the hiera datadir`

* Would it make sense to default the current working directory to `$ENV:Temp/Kitchen` in Windows?  This would allow us to specify a relative path in the hiera config (validated by `kitchen converge` and kicking off `puppet apply` from that path).  To avoid potential issues, you might introduce a `pwd`, `working_directory`, or some other provisioner option.
* Would it make sense to not hardcode the `hiera` ([here](https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L1237)) and instead use the provisioner option for `hiera_data_path`?

Cheers!

**Comment by neillturner** [comment]
1.  on linux it copies everything to /tmp/kitchen and runs in a shell under that directory. Of the top of my 
head the $ENV::Temp/Kitchen is windows equivalent of /tmp/kitchen. 
 The code generates the puppet command with full path names so doesn't require running in a particular directory. 
 you could try setting the parameter custom_pre_apply_command  to cd  $ENV:Temp/Kitchen
2. hiera data path
generally the approach is to copy various folders like hiera data path  to standard paths and then reference them in the puppet apply command via  hard coded values parameters. 

I will always looked at pull request or code changes. generally it is better to add an extra parameter in the kitchen.yml file and then add extra code so that everything is backward compatible.
