### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by gmoskovicz** [neillturner/kitchen-puppet#79]
Add support for running puppet on Windows hosts. Currently, this provisioner only works on unix host.

**Comment by neillturner** [comment]
Well it will work on windows if you have a sshd server installed and microsoft have promised for the third time to add ssh support. 
 that said winrm support is available in test-kitchen and should be relatively easy to add support to kitchen-puppet. I just have not had the time and in my past contract i didn't have the requirement. -)

**Comment by grubernaut** [comment]
I don't have the proper tooling setup to effectively test this on Windows, in order to add support. If anyone is Windows-savvy enough to tackle this, please do

**Comment by neillturner** [comment]
I don't actually believe that we have to change much code to make it work in windows. 
The first job is to get a windows test server running probably under vagrant and get the chef 
working via winrm. as per: 
http://www.hurryupandwait.io/blog/help-test-the-future-of-windows-infrastructure-testing-on-test-kitchen
http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/

once we have that then we just change our transport to winrm and start testing with the pupper provisioner.

**Comment by ramreddy26** [comment]
+1

**Comment by dgoade** [comment]
I have followed the steps in http://kitchen.ci/blog/test-kitchen-windows-test-flight-with-vagrant/, used the test-kitchen-1.4.2 gem and attempted to use puppet as the provisioner instead of Chef. The first obstacle I reached was "$$$$$$ The command line is too long." attempting Converge. I found that Matt Wrock recently added support for long winrm commands (https://github.com/test-kitchen/test-kitchen/commit/7318fa5bb93319b68303b0f93302f1c35bb8e562) so I tried the latest gem from master and I got bit further. Now,it just looks as if we need puppet_apply.rb to recognize and support the Windows platform os. A *long_script.ps script gets created on the Windows guest but the script is bash, not powershell. I guess a good start is https://github.com/neillturner/kitchen-puppet/blob/master/lib/kitchen/provisioner/puppet_apply.rb#L178. 

Is any of this helpful? Hope so.

**Comment by dgoade** [comment]
And then there is the fork of kitchen-puppet here, https://github.com/liamjbennett/kitchen-puppet which according to Liam himself was eventually abandoned for Beaker: http://tech.opentable.co.uk/blog/2014/09/01/testing-puppet-with-beaker-pt-dot-2-the-windows-story/

**Comment by grubernaut** [comment]
In my experience, using Beaker was better suited for running tests against single Puppet modules that worked in standalone. Fully using the `Infrastructure as code` principle, where the module itself was tested in isolation, similar to modules that are found on the puppet forge. 

Where I found the most benefit of using kitchen-puppet was at organizations that have a lot of custom interdependent modules that don't really work in isolation, and you need to test "the world" at a single time.

This could have very well changed recently, but I found beaker to be exceptionally better at testing puppet, and worked very well for testing single modules.

**Comment by neillturner** [comment]
I have been doing a little background on this. 

First I had to get a development environment for windows server so I got a free trial of azure and I'm getting kitchen-azurerm working and then i need to be able to rdp to the box and get chef deployment working (as this should already work). 

When i have this then i know i have a valid environment and i can then get puppet working. 
(the first version might just assume puppet is installed). 

In my next contract i might have a requirement for this and then I can do it has part of my job. Currently its just a spare time activity so it could be a couple of months to build.

**Comment by neillturner** [comment]
Also i've written a busser-beaker plugin which is designed to run tests specified in beaker format in test-kitchen. Beaker keeps the tests in the spec directory while test kitchen keeps them in something like  /test/integration/..... This is still experimental at this stage.

**Comment by neillturner** [comment]
this is now in version 1.43
